# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ynf < Formula
  desc "Your named factory: the event-driven outer loop around agent runs"
  homepage "https://github.com/eyelock/ynf"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eyelock/ynf/releases/download/v0.2.0/ynf_0.2.0_darwin_amd64.tar.gz"
      sha256 "9ec94ed67d488130c8fdb022e56c36b880b319346f30895c66373854dc0e3054"

      define_method(:install) do
        bin.install "ynf"
        libexec.install Dir["libexec/*"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eyelock/ynf/releases/download/v0.2.0/ynf_0.2.0_darwin_arm64.tar.gz"
      sha256 "82bfd387a250c67fb27c4759c5d3e6676fbc4e529027fd84668f666f39352f8b"

      define_method(:install) do
        bin.install "ynf"
        libexec.install Dir["libexec/*"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/eyelock/ynf/releases/download/v0.2.0/ynf_0.2.0_linux_amd64.tar.gz"
      sha256 "f7d3225403ff39b1562a7c94166914afe1e4439b978db05a24acc79486558048"
      define_method(:install) do
        bin.install "ynf"
        libexec.install Dir["libexec/*"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eyelock/ynf/releases/download/v0.2.0/ynf_0.2.0_linux_arm64.tar.gz"
      sha256 "162a1d3e801439bcfa1dfc07dd196c6ea42ecdbaf40004c4fed3185586ebc023"
      define_method(:install) do
        bin.install "ynf"
        libexec.install Dir["libexec/*"]
      end
    end
  end

  test do
    system "#{bin}/ynf", "version"
  end
end
