# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ynf < Formula
  desc "Your named factory: the event-driven outer loop around agent runs"
  homepage "https://github.com/eyelock/ynf"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eyelock/ynf/releases/download/v0.1.0/ynf_0.1.0_darwin_amd64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "9c51c5f9d23b06d0028f659afebd2649695afc61eb2a3d6c896763ffff753aee"

      define_method(:install) do
        bin.install "ynf"
        libexec.install Dir["libexec/*"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eyelock/ynf/releases/download/v0.1.0/ynf_0.1.0_darwin_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "32943ca20683ce9a1baaa01829e73e0368fa37aa94414fc7e06b85d97202a292"

      define_method(:install) do
        bin.install "ynf"
        libexec.install Dir["libexec/*"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/eyelock/ynf/releases/download/v0.1.0/ynf_0.1.0_linux_amd64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "362038451c63ec32e8d00ee813d5759aca43b046f393e97dc3ed90c60caf4af8"
      define_method(:install) do
        bin.install "ynf"
        libexec.install Dir["libexec/*"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eyelock/ynf/releases/download/v0.1.0/ynf_0.1.0_linux_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "5960d56a45f006c93663a0e7efd34a0a42a82c106a1ee4ab7fa99646516ce1e5"
      define_method(:install) do
        bin.install "ynf"
        libexec.install Dir["libexec/*"]
      end
    end
  end

  test do
    system "#{bin}/ynf", "version"
  end
end
