# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ynh < Formula
  desc "Harness template manager for AI coding assistants"
  homepage "https://github.com/eyelock/ynh"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eyelock/ynh/releases/download/v0.4.0/ynh_0.4.0_darwin_amd64.tar.gz"
      sha256 "169ab916c48e9e8ee64cadcbb6f04e0992389bb7c07ebadba9c4ac83dfc42fdf"

      define_method(:install) do
        bin.install "ynh"
        bin.install "ynd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eyelock/ynh/releases/download/v0.4.0/ynh_0.4.0_darwin_arm64.tar.gz"
      sha256 "9a0e4e7f50d1bb53d55a4e27bb3ae0d0587dc3351bf0dbc69833d824cc3195c7"

      define_method(:install) do
        bin.install "ynh"
        bin.install "ynd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/eyelock/ynh/releases/download/v0.4.0/ynh_0.4.0_linux_amd64.tar.gz"
      sha256 "ec4d0855fbabb857e85027c61e28181b0ab46a697e8a2e407cd4d0c8562d6670"
      define_method(:install) do
        bin.install "ynh"
        bin.install "ynd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eyelock/ynh/releases/download/v0.4.0/ynh_0.4.0_linux_arm64.tar.gz"
      sha256 "c1595619a6b495cb4f6f72d8e84599a84a87d47fd602fd63581f56006c08b4a1"
      define_method(:install) do
        bin.install "ynh"
        bin.install "ynd"
      end
    end
  end

  test do
    system "#{bin}/ynh", "version"
    system "#{bin}/ynd", "version"
  end
end
