# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ynh < Formula
  desc "Persona manager for AI coding assistants"
  homepage "https://github.com/eyelock/ynh"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eyelock/ynh/releases/download/v0.0.3/ynh_0.0.3_darwin_amd64.tar.gz"
      sha256 "07cb7cede4e6fa4c41da57426ac023ef820e5ebd624ddbaced3d381d507cecbe"

      def install
        bin.install "ynh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eyelock/ynh/releases/download/v0.0.3/ynh_0.0.3_darwin_arm64.tar.gz"
      sha256 "e887ca879736c66ed047355a785e968cbb1d88e1c0d335599e3e02d4cce09837"

      def install
        bin.install "ynh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/eyelock/ynh/releases/download/v0.0.3/ynh_0.0.3_linux_amd64.tar.gz"
      sha256 "1561ccdfcb40ae3e8fb590e8ce9fc086cfcf4497a8bea4e961f37e8d2f2a2e2d"
      def install
        bin.install "ynh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eyelock/ynh/releases/download/v0.0.3/ynh_0.0.3_linux_arm64.tar.gz"
      sha256 "536d70d3100e33976e79a3a06c708f28a222126e35fa27acd9983523b70d4c47"
      def install
        bin.install "ynh"
      end
    end
  end

  test do
    system "#{bin}/ynh", "version"
  end
end
