# typed: false
# frozen_string_literal: true

# This file is generated by the ynm release workflow. DO NOT EDIT.
class YnmSlim < Formula
  desc "Your named memory: agent memory in git notes over MCP and CLI"
  homepage "https://github.com/eyelock/ynm"
  url "https://github.com/eyelock/ynm/releases/download/v0.2.0/ynm_0.2.0_slim.tar.gz"
  sha256 "fdc865a43905799e339180c23855275d38783ecb42949d8f7a39053a1b467313"
  version "0.2.0"
  license "MIT"

  depends_on "git"
  depends_on "node"

  conflicts_with "ynm", because: "both install a `ynm` executable"

  def install
    libexec.install "ynm.mjs"
    bin.install "bin/ynm"
    # Run on Homebrew's node, whatever node is first on PATH.
    inreplace bin/"ynm", 'node="${YNM_NODE:-node}"',
              "node=\"\${YNM_NODE:-#{Formula["node"].opt_bin}/node}\""
  end

  test do
    assert_match "@ynm/cli/#{version}", shell_output("#{bin}/ynm --version")
    system "#{bin}/ynm", "serve", "--help"
  end
end
