# typed: false
# frozen_string_literal: true

# This file is generated by the ynm release workflow. DO NOT EDIT.
class YnmSlim < Formula
  desc "Your named memory: agent memory in git notes over MCP and CLI"
  homepage "https://github.com/eyelock/ynm"
  url "https://github.com/eyelock/ynm/releases/download/v0.4.1/ynm_0.4.1_slim.tar.gz"
  sha256 "23a6b6f9b74c033d8083d957b6ae931bed38c6e330996a74f83ff51c17e7cfa4"
  version "0.4.1"
  license "MIT"

  depends_on "git"
  depends_on "node"

  conflicts_with "ynm", because: "both install a `ynm` executable"

  def install
    libexec.install "ynm.mjs"
    bin.install "bin/ynm"
    # Run on Homebrew's node, whatever node is first on PATH.
    inreplace bin/"ynm", 'node="${YNM_NODE:-node}"',
              "node=\"\${YNM_NODE:-#{Formula["node"].opt_bin}/node}\""
  end

  test do
    assert_match "@ynm/cli/#{version}", shell_output("#{bin}/ynm --version")
    system "#{bin}/ynm", "serve", "--help"
  end
end
