# typed: false
# frozen_string_literal: true

# This file is generated by the ynm release workflow. DO NOT EDIT.
class Ynm < Formula
  desc "Your named memory: agent memory in git notes over MCP and CLI"
  homepage "https://github.com/eyelock/ynm"
  version "0.4.0"
  license "MIT"

  depends_on "git"

  conflicts_with "ynm-slim", because: "both install a `ynm` executable"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eyelock/ynm/releases/download/v0.4.0/ynm_0.4.0_darwin_amd64.tar.gz"
      sha256 "c077fe2990aed4f73b0782276257434d1e996d41b383caed4c3f990d06fd7664"

      define_method(:install) do
        bin.install "ynm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eyelock/ynm/releases/download/v0.4.0/ynm_0.4.0_darwin_arm64.tar.gz"
      sha256 "ecabc4115d7195be38b738fa3d286a86253178249cd3d60c87b455eaa13ab244"

      define_method(:install) do
        bin.install "ynm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/eyelock/ynm/releases/download/v0.4.0/ynm_0.4.0_linux_amd64.tar.gz"
      sha256 "dd370c7381d2ae507b880d157e2fcdedcda10032bfa0dfc2edfccb0b9e5bd1f5"

      define_method(:install) do
        bin.install "ynm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eyelock/ynm/releases/download/v0.4.0/ynm_0.4.0_linux_arm64.tar.gz"
      sha256 "437987f50badf277e9c800667ea67eb8c25c35413248ee958c659b684cf52b15"

      define_method(:install) do
        bin.install "ynm"
      end
    end
  end

  test do
    assert_match "@ynm/cli/#{version}", shell_output("#{bin}/ynm --version")
    system "#{bin}/ynm", "serve", "--help"
  end
end
