# typed: false
# frozen_string_literal: true

# This file is generated by the ynm release workflow. DO NOT EDIT.
class Ynm < Formula
  desc "Your named memory: agent memory in git notes over MCP and CLI"
  homepage "https://github.com/eyelock/ynm"
  url "https://github.com/eyelock/ynm/releases/download/v0.1.0/ynm-0.1.0.tar.gz"
  sha256 "a31e6c365c53d27b4cbf65bb8b05df92a5bcb41d740d482892c2252fc921bfd8"
  version "0.1.0"
  license "MIT"

  depends_on "git"
  depends_on "node"

  def install
    libexec.install Dir["*"]
    (bin/"ynm").write_env_script libexec/"bin/run.js", PATH: "#{Formula["node"].opt_bin}:$PATH"
  end

  test do
    assert_match "@ynm/cli", shell_output("#{bin}/ynm --version")
    system "#{bin}/ynm", "serve", "--help"
  end
end
